name: Docker Compose Acrions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose
        run: docker-compose -f "docker-compose-github-actions.yml" up -d
        env:
          POSTGRES_USERNAME: ${{ secrets.POSTGRES_USERNAME }}
          POSTGRES_HOSTNAME: "127.0.0.1"
          POSTGRES_PORT: "4012"
          POSTGRES_DB_NAME: ${{ secrets.POSTGRES_DB_NAME }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}